language: php
php:
  - 7.0
  - 5.4
  - 5.5
  - 5.6
  - hhvm
install:
  - composer install --no-dev --quiet
notifications:
  email:
    recipients:
      - yasinyaqoobi@gmail.com
    on_success: change
    on_failure: always
script: phpunit -c phpunit.xml --coverage-text